version: '3.5'

services:
  example-app:
    build: .
    ports:
      - 8888:80
    networks:
      - proxy-network
    # volumes:
    #   - './src:/app'
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.rule=Host:example-app.local.usacycling.org"
      - "traefik.port=80"
    environment:
      - APP_ENV=development
      - CHOKIDAR_USEPOLLING=true

networks:
  proxy-network:
    external:
      name: usac-dev
